Repository heyimjustalex/TagMedX, pull requests merged in 2023-11, with the labels that each got.

#20 Feature: authorization and session
  backend/features/authorization/controllers/token_controller.py
  frontend/.eslintrc.js
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/groups/layout.jsx
  frontend/src/app/groups/page.jsx
  frontend/src/app/page.jsx
  frontend/src/app/providers.jsx
  frontend/src/components/LoginForm/LoginForm.jsx
  frontend/src/components/LoginForm/LoginFormConsts.js
  frontend/src/components/LoginForm/LoginFormUtils.js
  frontend/src/components/Nav/Nav.jsx
  frontend/src/components/Nav/NavUtils.js
  frontend/src/components/NavDesktop/NavDesktop.jsx
  frontend/src/components/NavDesktop/NavDesktopConsts.js
  frontend/src/components/NavMobile/NavMobile.jsx
  frontend/src/components/NavMobile/NavMobileConsts.js
  frontend/src/components/ProtectedRoute/ProtectedRoute.jsx
  frontend/src/components/SignupForm/SignupForm.jsx
  frontend/src/components/SignupForm/SignupFormUtils.js
  frontend/src/consts/NextColor.js
  frontend/src/consts/Status.js
  frontend/src/contexts/NotificationContext.js
  frontend/src/contexts/UserIdContext.js
  frontend/src/hooks/useNotification.js
  frontend/src/hooks/useUserId.js
  frontend/src/utils/cookie.js
  frontend/src/utils/localSession.js
  frontend/src/utils/serverSession.js
Labels: enhancement

#24 Feature: groups page
  frontend/src/app/globals.css
  frontend/src/app/groups/page.jsx
  frontend/src/app/page.jsx
  frontend/src/components/GroupsTable/GroupsTable.jsx
  frontend/src/components/GroupsTable/GroupsTableAddModal.jsx
  frontend/src/components/GroupsTable/GroupsTableConsts.jsx
  frontend/src/components/GroupsTable/GroupsTableJoinModal.jsx
  frontend/src/components/GroupsTable/GroupsTableTopContent.jsx
  frontend/src/components/GroupsTable/GroupsTableUtils.jsx
  frontend/src/components/LoginForm/LoginFormConsts.jsx
  frontend/src/components/LoginForm/LoginFormUtils.jsx
  frontend/src/components/Nav/Nav.jsx
  frontend/src/components/Nav/NavConsts.jsx
  frontend/src/components/Nav/NavDesktop/NavDesktop.jsx
  frontend/src/components/Nav/NavMobile/NavMobile.jsx
  frontend/src/components/Nav/NavMobile/NavMobileConsts.jsx
  frontend/src/components/Nav/NavUtils.jsx
  frontend/src/components/NavDesktop/NavDesktopConsts.js
  frontend/src/components/Notification/Notification.jsx
  frontend/src/components/Notification/NotificationUtils.jsx
  frontend/src/components/SignupForm/SignupForm.jsx
  frontend/src/components/SignupForm/SignupFormConsts.jsx
  frontend/src/components/SignupForm/SignupFormUtils.jsx
  frontend/src/consts/NextColorMap.js
  frontend/src/utils/fetch.js
Labels: enhancement

#27 DB: Package entity add, schema changed
  DB/2.PNG
  DB/dbdiagram.txt
  DB/setup.sql
  README.md
  backend/.vs/ProjectSettings.json
  backend/.vs/VSWorkspaceState.json
  backend/.vs/backend/v17/.wsuo
  backend/.vs/slnx.sqlite
  backend/app.py
  backend/features/label/controllers/label_controller.py
  backend/features/label/schemas/label_schema.py
  backend/features/label/services/label_service.py
  backend/features/sets/__init__.py
  backend/features/sets/controllers/__init__.py
  backend/features/sets/controllers/set_controller.py
  backend/features/sets/schemas/__init__.py
  backend/features/sets/schemas/set_schema.py
  backend/features/sets/services/__init__.py
  backend/features/sets/services/set_service.py
  backend/features/tasks/controllers/task_controller.py
  backend/features/tasks/services/task_service.py
  backend/models/models.py
  backend/repositories/group_repository.py
  backend/repositories/label_repository.py
  backend/repositories/set_repository.py
  backend/repositories/task_repository.py
Labels: change

#29 Feature: group settings
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/groups/[id]/page.jsx
  frontend/src/app/groups/page.jsx
  frontend/src/components/Group/Group.jsx
  frontend/src/components/Group/GroupSettings/GroupSettings.jsx
  frontend/src/components/Group/GroupSettings/GroupSettingsUtils.jsx
  frontend/src/components/Group/GroupUsers/GroupUsers.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersConsts.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersModal.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersTopContent.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersUtils.jsx
  frontend/src/components/GroupsTable/GroupsTableAddModal.jsx
  frontend/src/components/GroupsTable/GroupsTableJoinModal.jsx
  frontend/src/consts/NextColorMap.js
  frontend/src/utils/fetch.js
  frontend/src/utils/serverFetch.js
  frontend/src/utils/text.js
Labels: enhancement

#31 Feature: enhanced group users table
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/groups/[id]/page.jsx
  frontend/src/components/Group/GroupSettings/GroupSettings.jsx
  frontend/src/components/Group/GroupSettings/GroupSettingsUtils.jsx
  frontend/src/components/Group/GroupUsers/GroupUsers.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersConsts.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersModal.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersTopContent.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersUtils.jsx
  frontend/src/components/GroupsTable/GroupsTableTopContent.jsx
Labels: enhancement

#34 Feature: profile page
  backend/features/groups/controllers/group_controller.py
  frontend/src/app/groups/[id]/page.jsx
  frontend/src/app/page.jsx
  frontend/src/app/profile/layout.jsx
  frontend/src/app/profile/page.jsx
  frontend/src/components/Group/Group.jsx
  frontend/src/components/Group/GroupSettings/GroupSettings.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersUtils.jsx
  frontend/src/components/GroupsTable/GroupsTableTopContent.jsx
  frontend/src/components/LoginForm/LoginForm.jsx
  frontend/src/components/Nav/Nav.jsx
  frontend/src/components/Nav/NavConsts.jsx
  frontend/src/components/Nav/NavDesktop/NavDesktop.jsx
  frontend/src/components/Nav/NavMobile/NavMobile.jsx
  frontend/src/components/Profile/Profile.jsx
  frontend/src/components/Profile/ProfileConsts.jsx
  frontend/src/components/Profile/ProfileUtils.jsx
  frontend/src/components/SignupForm/SignupForm.jsx
  frontend/src/consts/Specializations.js
  frontend/src/consts/Titles.js
  frontend/src/utils/text.js
Labels: bug, enhancement

#38 Feature: sets page
  DB/setup.sql
  backend/features/groups/controllers/group_controller.py
  backend/features/sets/controllers/set_controller.py
  backend/features/sets/schemas/set_schema.py
  frontend/src/app/groups/[id]/page.jsx
  frontend/src/app/groups/page.jsx
  frontend/src/app/login/layout.jsx
  frontend/src/app/profile/page.jsx
  frontend/src/app/signup/layout.jsx
  frontend/src/components/Group/Group.jsx
  frontend/src/components/Group/GroupSets/GroupSets.jsx
  frontend/src/components/Group/GroupSets/GroupSetsConsts.jsx
  frontend/src/components/Group/GroupSets/GroupSetsModal.jsx
  frontend/src/components/Group/GroupSets/GroupSetsRemoveModal.jsx
  frontend/src/components/Group/GroupSets/GroupSetsTopContent.jsx
  frontend/src/components/Group/GroupSets/GroupSetsUtils.jsx
  frontend/src/components/Group/GroupSettings/GroupSettings.jsx
  frontend/src/components/Group/GroupSettings/GroupSettingsUtils.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersUtils.jsx
  frontend/src/components/GroupsTable/GroupsTableAddModal.jsx
  frontend/src/components/Profile/Profile.jsx
  frontend/src/components/Profile/ProfileConsts.jsx
  frontend/src/components/Profile/ProfileUtils.jsx
  frontend/src/consts/NextColorMap.js
  frontend/src/utils/serverFetch.js
  frontend/src/utils/serverSession.js
Labels: enhancement

#42 Feature: packages and samples
  DB/setup.sql
  backend/features/packages/controllers/package_controller.py
  frontend/src/app/groups/[id]/page.jsx
  frontend/src/components/Group/Group.jsx
  frontend/src/components/Group/GroupPackages/GroupPackage.jsx
  frontend/src/components/Group/GroupPackages/GroupPackages.jsx
  frontend/src/components/Group/GroupPackages/GroupPackagesUtils.jsx
  frontend/src/components/Group/GroupSets/GroupSets.css
  frontend/src/components/Group/GroupSets/GroupSets.jsx
  frontend/src/components/Group/GroupSets/GroupSetsConsts.jsx
  frontend/src/components/Group/GroupSets/GroupSetsModal.jsx
  frontend/src/components/Group/GroupSets/GroupSetsRemoveModal.jsx
  frontend/src/components/Group/GroupSets/GroupSetsSamplesModal.jsx
  frontend/src/components/Group/GroupSets/GroupSetsTopContent.jsx
  frontend/src/components/Group/GroupSets/GroupSetsUtils.jsx
  frontend/src/components/Group/GroupSettings/GroupSettings.jsx
  frontend/src/components/Group/GroupUsers/GroupUsers.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersModal.jsx
  frontend/src/components/Group/GroupUsers/GroupUsersTopContent.jsx
  frontend/src/components/GroupsTable/GroupsTable.jsx
  frontend/src/components/GroupsTable/GroupsTableAddModal.jsx
  frontend/src/components/GroupsTable/GroupsTableJoinModal.jsx
  frontend/src/components/GroupsTable/GroupsTableTopContent.jsx
  frontend/src/utils/fetch.js
  frontend/tailwind.config.js
Labels: enhancement
